{% set version = "0.17.2" %}

package:
  name: pyrsistent
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyrsistent/pyrsistent-{{ version }}.tar.gz
  sha256: 27515d2d5db0629c7dadf6fbe76973eb56f098c1b01d36de42eb69220d2c19e4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyrsistent
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/tobgu/pyrsistent/
  license: MIT
  license_family: MIT
  license_file: LICENCE.mit
  summary: Persistent/Functional/Immutable data structures

extra:
  recipe-maintainers:
    - ocefpaf
