{% set version = "0.15.2" %}

package:
  name: pyrsistent
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyrsistent/pyrsistent-{{ version }}.tar.gz
  sha256: 16692ee739d42cf5e39cef8d27649a8c1fdb7aa99887098f1460057c5eb75c3a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - six
    - pytest-runner
  run:
    - python
    - six

test:
  imports:
    - pyrsistent
  requires:
    - hypothesis
    - pytest

about:
  home: http://github.com/tobgu/pyrsistent/
  license: MIT
  license_family: MIT
  license_file: LICENCE.mit
  summary: Persistent/Functional/Immutable data structures

extra:
  recipe-maintainers:
    - ocefpaf
