{% set version = "0.14.8" %}

package:
  name: pyrsistent
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyrsistent/pyrsistent-{{ version }}.tar.gz
  sha256: 59880cc33ac293515892b2969aa8f4ed2cec592cbd0be4c4e20f2410468bbc62

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - six
    - pytest-runner
  run:
    - python
    - six

test:
  imports:
    - pyrsistent
  requires:
    - hypothesis
    - pytest

about:
  home: http://github.com/tobgu/pyrsistent/
  license: MIT
  license_family: MIT
  license_file: LICENCE.mit
  summary: Persistent/Functional/Immutable data structures

extra:
  recipe-maintainers:
    - ocefpaf
