# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "v3k5ww7E6ZZfltYoGZN5IMI8PlFESTGza5aX+jKPfw6bG0C2ltWCrQHpK6YjHqes+Kr0EN2iP2vO6+Yc0eAXOP/CegGXH7Ei4l8sofqL1gWDUbL3FoVNj2/Z6lrD+mV7/tb5f3FyUqFBpffRAR2iicf7x37oe9VoTy3Zqz8RxlKgUrQivhI4jot3A9/HZWd+rtiOC1/DwMINYZiN8JWFdBwnjCT80Jy9cr4drFlffi+DFcxkOpB6O/bvidiKPkgHN39gW76nlY95UZE9ANZSdL+jSo5BuB7pQE2x7WF2MdaV4vAYfnlE+H2aBXinpPQZfzCd+/Ym6lhUH4Pg3HOLRzS4rrBE33Z48sXyEyIiNk5tPzaO1DzFLHTOuDIxITWGBQNqztC859qu5fO/wIqmB16w/8BLIZ1NWvqF7hV6VPsm7K13ezIX9A/vVpSo9FsiTAoznHi5Avb4p6O1pvAIqC99SoJDBEE1ioTApISYYH0hD4XI6D0HkDqlZjthXlTbkaZ0odvC0WYFyjHlckRaQkMRhtCPjJiaoAeC+RMhrpYQJaVLAZu1SXIflc61NZpm2j69R9a/ItLIEjU7L6+ggbsSZm6XqkXM5IrCNPbuvfsJedZdfHZN9g68hxXfqZ58S7rNP2i9tLJBsWmA3nzgoB5JVRnJA3Z+01Bz42qO17o="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
